import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'NoteHub',
  description: 'Generated by create next app',
};
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import TanstackProvider from '@/components/TanstackProvider/TanstackProvider';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TanstackProvider>
          <Header />
          <main className="content">{children}</main>
          <div id="modal-root"></div>
          <Footer />
        </TanstackProvider>
      </body>
    </html>
  );
}
